version:  '3.21'

name: kafkalyze-local-development

services:
  zookeeper:
    container_name: kafkalyze-local-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/app
    networks:
      - kafkalyze
    restart: always

  kafka:
    container_name: kafkalyze-local-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_data:/app
    networks:
      - kafkalyze
    restart: always
    depends_on:
      - zookeeper

  mongo:
    container_name: kafkalyze-local-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/app
    networks:
      - kafkalyze
    restart: always

volumes:
  zookeeper_data:
  kafka_data:
  mongo_data:
  prometheus_data:

networks:
  kafkalyze:
