version:  '3.21'

name: kafkalyze-local-development

services:
  zookeeper:
    container_name: kafkalyze-local-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/app
    networks:
      - kafkalyze
    restart: always

  kafka:
    container_name: kafkalyze-local-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/app
    networks:
      - kafkalyze
    restart: always
    depends_on:
      - zookeeper

  mongo:
    container_name: kafkalyze-local-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/app
    networks:
      - kafkalyze
    restart: always

  prometheus:
    container_name: kafkalyze-local-prometheus
    image: bitnami/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/app
    networks:
      kafkalyze:
    restart: always

volumes:
  zookeeper_data:
  kafka_data:
  mongo_data:
  prometheus_data:

networks:
  kafkalyze:
