openapi: 3.0.3
info:
  title: "Kafkalyze API"
  description: "API documentation for the Kafkalyze server"
  version: "0.0.1"
externalDocs:
  description: "Find out more about Kafkalyze"
  url: "https://github.com/tntmeijs/kafkalyze"
servers:
  - url: "http://localhost:8080"
tags:
  - name: "events"
    description: "Kafka event operations"
  - name: "topics"
    description: "Kafka topic operations"
  - name: "consumers"
    description: "Kafka consumer operations"
  - name: "statistics"
    description: "Statistics for dashboarding purposes"
  - name: "system"
    description: "Server information"
paths:
  /api/v1/topics:
    get:
      tags:
        - "topics"
      summary: "Fetch all topics"
      description: "Fetch all available topics on the Kafka broker"
      operationId: "getAllTopics"
      responses:
        "200":
          description: "Successfully fetched topic information"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicInformationV1"
    post:
      tags:
        - "topics"
      summary: "Create a new topic"
      description: "Create a new topic on the Kafka broker"
      operationId: "createNewTopic"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNewTopicV1"
      responses:
        "200":
          description: "Successfully created the new topic"
        "400":
          description: "Failed to create the new topic"
  /api/v1/topics/{name}:
    delete:
      tags:
        - "topics"
      summary: "Delete an existing topic"
      description: "Delete an existing topic from the Kafka broker"
      operationId: "deleteExistingTopic"
      parameters:
        - in: path
          name: "name"
          schema:
            type: string
            example: "dev.tahar.topic.sample.a"
          required: true
          description: "Name of the topic to delete"
      responses:
        "200":
          description: "Successfully deleted the topic"
        "400":
          description: "Failed to delete the topic"
  /api/v1/consumers:
    get:
      tags:
        - "consumers"
      summary: "Fetch all consumer groups in the cluster"
      description: "Fetch all consumer groups in the cluster"
      operationId: "fetchConsumerGroups"
      parameters:
        - in: query
          name: status
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              enum: ["UNKNOWN", "PREPARING_REBALANCE", "COMPLETING_REBALANCE", "STABLE", "DEAD", "EMPTY"]
          description: "Only display consumer groups with any of the provided statuses"
      responses:
        "200":
          description: "Consumer groups were fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KafkaConsumerGroups"
  /api/v1/events:
    post:
      tags:
        - "events"
      summary: "Produce a message to Kafka"
      description: "Produce a string message to the specified Kafka topic"
      operationId: "produceStringEventV1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProduceStringEventV1"
      responses:
        "200":
          description: "Event was produced"
  /api/v1/statistics/kafka/events/storage:
    get:
      tags:
        - "statistics"
      summary: "Fetch statistics about how much storage Kafka events take up in Kafkalyze"
      description: "Fetch statistics about Kafka events such as how many events are stored"
      operationId: "fetchEventStorageStatistics"
      responses:
        "200":
          description: "Statistics were fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventStorageStatisticsV1"
  /api/v1/statistics/kafka/events/distribution:
    get:
      tags:
        - "statistics"
      summary: "Fetch statistics about how Kafka events are distributed over topics"
      description: "Fetch statistics about the number of events consumed per topic within a given timeframe"
      operationId: "fetchEventDistributionStatistics"
      parameters:
        - in: query
          name: minTimestampMs
          required: true
          schema:
            type: integer
            format: int64
          description: "Use this to adjust how old the data can be"
        - in: query
          name: maxTimestampMs
          required: true
          schema:
            type: integer
            format: int64
          description: "Use this to adjust how recent the data can be"
      responses:
        "200":
          description: "Statistics were fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventDistributionStatisticsV1"
  /api/v1/statistics/kafka/events/consumed:
    get:
      tags:
        - "statistics"
      summary: "Fetch statistics about Kafka events consumed"
      description: "Fetch statistics about the number of events consumed within a given timeframe"
      operationId: "fetchEventConsumptionStatistics"
      parameters:
        - in: query
          name: minTimestampMs
          required: true
          schema:
            type: integer
            format: int64
          description: "Use this to adjust how old the data can be"
        - in: query
          name: maxTimestampMs
          required: true
          schema:
            type: integer
            format: int64
          description: "Use this to adjust how recent the data can be"
        - in: query
          name: intervalMs
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: "The granularity of the interval in milliseconds between each datapoint"
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 10000
          description: "The number of desired results"
      responses:
        "200":
          description: "Statistics were fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventConsumptionStatisticsV1"
  /api/v1/statistics/kafka/cluster:
    get:
      tags:
        - "statistics"
      summary: "Fetch statistics about the Kafka cluster"
      description: "Fetch statistics about the cluster currently connected to Kafkalyze"
      operationId: "fetchClusterStatistics"
      responses:
        "200":
          description: "Cluster statistics were fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KafkaClusterStatistics"
  /api/v1/system/liveness:
    get:
      tags:
        - "system"
      summary: "Check if the server is running"
      description: "Use this endpoint to check if the server can be reached at all"
      operationId: "livenessProbe"
      responses:
        "200":
          description: "Server is up and running"
components:
  schemas:
    TopicInformationV1:
      type: object
      description: "List of all available topics on the Kafka broker"
      properties:
        topics:
          type: array
          items:
            type: string
          example: [ "dev.tahar.topic.sample.a", "dev.tahar.topic.sample.b" ]
    CreateNewTopicV1:
      type: object
      description: "Information needed to create a new topic"
      properties:
        name:
          type: string
          example: "dev.tahar.topic.sample.a"
        partitionCount:
          type: integer
          example: 4
        replicationFactor:
          type: integer
          example: 2
    ProduceStringEventV1:
      type: object
      description: "Payload needed to produce the event to Kafka"
      properties:
        data:
          type: string
          example: "{ \"key\": \"hello\", \"value\": \"world\" }"
        topic:
          type: string
          example: "dev.tahar.topic.sample.a"
    EventStorageStatisticsV1:
      type: object
      description: "Statistics about consumed events' storage"
      properties:
        databaseSizeInBytes:
          type: integer
          format: int64
          example: 1500000000
        eventCount:
          type: integer
          format: int64
          example: 5500
    EventDistributionStatisticsV1:
      type: object
      description: "Statistics about consumed events' distribution over topics"
      properties:
        eventDistributionPerTopic:
          type: object
          additionalProperties:
            type: integer
            format: int64
    EventConsumptionStatisticsV1:
      type: object
      description: "Statistics about event consumption"
      properties:
        eventsConsumedAtTimeframe:
          type: object
          additionalProperties:
            type: integer
            format: int64
    KafkaClusterStatistics:
      type: object
      description: "Kafka cluster statistics"
      properties:
        nodes:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 1
              hostname:
                type: string
                example: "localhost"
              port:
                type: integer
                example: 9093
              rack:
                type: string
                example: "rack-identifier"
              isClusterController:
                type: boolean
                example: true
    KafkaConsumerGroups:
      type: object
      description: "Kafka consumer groups information"
      properties:
        consumerGroups:
          type: array
          items:
            type: object
            properties:
              groupId:
                type: string
                example: "consumer-group-one"
